# Generated for Skatlaz Server AI 2.0 beta
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='AgentCategory', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120, unique=True)), ('slug', models.SlugField(max_length=140, unique=True)), ('description', models.TextField(blank=True))]),
        migrations.CreateModel(name='LLMProvider', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120, unique=True)), ('provider_type', models.CharField(choices=[('ollama','Ollama Local'),('gemini','Google Gemini'),('openai','OpenAI compatible'),('custom','Custom HTTP')], max_length=32)), ('base_url', models.CharField(blank=True, default='http://localhost:11434', max_length=300)), ('api_key_env', models.CharField(blank=True, help_text='Environment variable that stores the API key', max_length=120)), ('default_model', models.CharField(blank=True, max_length=120)), ('embedding_model', models.CharField(blank=True, default='nomic-embed-text', max_length=120)), ('enabled', models.BooleanField(default=True))]),
        migrations.CreateModel(name='PromptTemplate', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120, unique=True)), ('category', models.CharField(blank=True, db_index=True, max_length=80)), ('system_prompt', models.TextField(default='You are Skatlaz Server AI, a helpful generative AI server.')), ('user_template', models.TextField(default='{question}\n\nContext:\n{context}')), ('temperature', models.FloatField(default=0.2)), ('top_p', models.FloatField(default=0.9)), ('active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='RAGCollection', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120, unique=True)), ('description', models.TextField(blank=True)), ('embedding_model', models.CharField(blank=True, default='nomic-embed-text', max_length=120)), ('vector_backend', models.CharField(default='sqlite', help_text='sqlite, chroma, faiss', max_length=40)), ('enabled', models.BooleanField(default=True)), ('embedding_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.llmprovider'))]),
        migrations.CreateModel(name='AIAgent', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120, unique=True)), ('model_name', models.CharField(blank=True, max_length=120)), ('description', models.TextField(blank=True)), ('tools', models.JSONField(blank=True, default=list, help_text='Examples: rag, webdiver, python, image_search')), ('enabled', models.BooleanField(default=True)), ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='ai_core.agentcategory')), ('prompt_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.prompttemplate')), ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.llmprovider'))]),
        migrations.CreateModel(name='ChatSession', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('title', models.CharField(blank=True, max_length=200)), ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.aiagent')), ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='DocumentSource', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('source_type', models.CharField(choices=[('upload','Upload'),('web','WebDiver URL'),('csv','CSV'),('manual','Manual text')], default='upload', max_length=20)), ('title', models.CharField(max_length=240)), ('url', models.URLField(blank=True)), ('file', models.FileField(blank=True, null=True, upload_to='rag_uploads/')), ('raw_text', models.TextField(blank=True)), ('metadata', models.JSONField(blank=True, default=dict)), ('indexed', models.BooleanField(default=False)), ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ai_core.ragcollection'))]),
        migrations.CreateModel(name='TrainingDataset', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120, unique=True)), ('file', models.FileField(blank=True, null=True, upload_to='datasets/')), ('format_type', models.CharField(choices=[('chat','Chat JSONL'),('instruct','Instruction'),('csv','CSV'),('rag','RAG chunks')], default='instruct', max_length=20)), ('prepared_path', models.CharField(blank=True, max_length=300)), ('notes', models.TextField(blank=True)), ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.agentcategory')), ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.ragcollection'))]),
        migrations.CreateModel(name='WebDiverTask', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('url', models.URLField()), ('diver_type', models.CharField(default='_text', help_text='_text, _html, _filter, _download', max_length=20)), ('database_path', models.CharField(default='db_webdiver.sqlite', max_length=300)), ('status', models.CharField(choices=[('pending','Pending'),('running','Running'),('done','Done'),('error','Error')], default='pending', max_length=20)), ('result_text', models.TextField(blank=True)), ('error', models.TextField(blank=True)), ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.ragcollection'))]),
        migrations.CreateModel(name='RAGChunk', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('text', models.TextField()), ('embedding', models.JSONField(blank=True, default=list)), ('metadata', models.JSONField(blank=True, default=dict)), ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_core.ragcollection')), ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_core.documentsource'))]),
        migrations.CreateModel(name='FineTuneJob', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=120, unique=True)), ('base_model', models.CharField(default='llama3.1', max_length=160)), ('method', models.CharField(choices=[('lora','LoRA'),('qlora','QLoRA'),('modelfile','Ollama Modelfile only')], default='qlora', max_length=20)), ('hyperparameters', models.JSONField(blank=True, default=dict)), ('status', models.CharField(choices=[('draft','Draft'),('queued','Queued'),('running','Running'),('done','Done'),('error','Error')], default='draft', max_length=20)), ('output_dir', models.CharField(blank=True, max_length=300)), ('modelfile_path', models.CharField(blank=True, max_length=300)), ('ollama_model_name', models.CharField(blank=True, max_length=120)), ('log', models.TextField(blank=True)), ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.aiagent')), ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.trainingdataset'))]),
        migrations.CreateModel(name='ChatMessage', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('role', models.CharField(choices=[('user','User'),('assistant','Assistant'),('system','System'),('tool','Tool')], max_length=20)), ('content', models.TextField()), ('model_name', models.CharField(blank=True, max_length=120)), ('metadata', models.JSONField(blank=True, default=dict)), ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_core.llmprovider')), ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_core.chatsession'))]),
        migrations.AddIndex(model_name='ragchunk', index=models.Index(fields=['collection', 'created_at'], name='ai_core_rag_collect_5166c5_idx')),
    ]
